from sqlalchemy import Column, String, Integer, Float, Boolean, ForeignKey, DateTime, Text, JSON, create_engine
from sqlalchemy.orm import declarative_base, relationship, sessionmaker
from datetime import datetime
from backend.config import settings
from backend.utils import encrypt_api_key, decrypt_api_key

Base = declarative_base()

class Merchant(Base):
    __tablename__ = 'merchants'
    
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    company_name = Column(String, nullable=True)
    industry = Column(String, nullable=True)
    email = Column(String, unique=True, nullable=False)
    password_hash = Column(String, nullable=False)
    encrypted_razorpay_key = Column(String, nullable=True) # AES-256-GCM encrypted
    encrypted_razorpay_secret = Column(String, nullable=True)
    encrypted_webhook_secret = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def set_secrets(self, plain_key: str, plain_secret: str, plain_whsec: str):
        self.encrypted_razorpay_key = encrypt_api_key(plain_key) if plain_key else None
        self.encrypted_razorpay_secret = encrypt_api_key(plain_secret) if plain_secret else None
        self.encrypted_webhook_secret = encrypt_api_key(plain_whsec) if plain_whsec else None
        
    def get_razorpay_key(self) -> str:
        return decrypt_api_key(self.encrypted_razorpay_key) if self.encrypted_razorpay_key else ""
        
    def get_razorpay_secret(self) -> str:
        return decrypt_api_key(self.encrypted_razorpay_secret) if self.encrypted_razorpay_secret else ""
        
    def get_webhook_secret(self) -> str:
        return decrypt_api_key(self.encrypted_webhook_secret) if self.encrypted_webhook_secret else ""

class Customer(Base):
    __tablename__ = 'customers'
    
    id = Column(String, primary_key=True) # cyvault_cust_id
    merchant_id = Column(String, ForeignKey('merchants.id'), nullable=False)
    phone = Column(String, nullable=True)
    email = Column(String, nullable=True)
    device_fingerprint = Column(String, nullable=True) # Critical for Entity Graph (Fraud Rings)
    is_blocked = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

class Order(Base):
    __tablename__ = 'orders'
    
    id = Column(String, primary_key=True) # rzp_order_id
    merchant_id = Column(String, ForeignKey('merchants.id'), nullable=False)
    customer_id = Column(String, ForeignKey('customers.id'), nullable=False)
    amount_paise = Column(Integer, nullable=False)
    currency = Column(String, default="INR")
    status = Column(String, nullable=False) # created, paid, attempted
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    customer = relationship("Customer")

class Transaction(Base):
    __tablename__ = 'transactions'
    
    id = Column(String, primary_key=True) # rzp_pay_id
    order_id = Column(String, ForeignKey('orders.id'), nullable=False)
    amount_paise = Column(Integer, nullable=False)
    status = Column(String, nullable=False) # captured, failed, authorized
    method = Column(String, nullable=False) # upi, card, netbanking
    error_code = Column(String, nullable=True)
    error_description = Column(Text, nullable=True)
    risk_score = Column(Float, nullable=True) # Generated by ML Model
    created_at = Column(DateTime, default=datetime.utcnow)

class Settlement(Base):
    __tablename__ = 'settlements'
    
    id = Column(String, primary_key=True) # rzp_setl_id
    merchant_id = Column(String, ForeignKey('merchants.id'), nullable=False)
    amount_paise = Column(Integer, nullable=False)
    fees_paise = Column(Integer, nullable=False)
    tax_paise = Column(Integer, nullable=False)
    utr = Column(String, nullable=True)
    status = Column(String, nullable=False) # processed, created, failed
    created_at = Column(DateTime, default=datetime.utcnow)

class PolicyRule(Base):
    """Feature 2: Governed Action Ledger - compiled rules"""
    __tablename__ = 'policy_rules'
    
    id = Column(String, primary_key=True)
    merchant_id = Column(String, ForeignKey('merchants.id'), nullable=False)
    name = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    rule_type = Column(String, nullable=False) # spend_limit, retry_cap, approval_threshold
    parameters = Column(JSON, nullable=False) # e.g. {"max_discount": 5, "max_retries": 3}
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

class ActionReceipt(Base):
    """Feature 2: Governed Action Ledger - Audit Trail"""
    __tablename__ = 'action_receipts'
    
    id = Column(String, primary_key=True)
    merchant_id = Column(String, ForeignKey('merchants.id'), nullable=False)
    action_type = Column(String, nullable=False) # e.g. "offer_discount", "retry_payment"
    entity_id = Column(String, nullable=False) # target order or customer
    policy_id = Column(String, ForeignKey('policy_rules.id'), nullable=True)
    decision = Column(String, nullable=False) # ALLOWED, BLOCKED, NEEDS_APPROVAL
    narrative = Column(Text, nullable=False) # Plain English explanation of why
    created_at = Column(DateTime, default=datetime.utcnow)

# Database Setup
db_url = settings.DATABASE_URL

engine = create_engine(db_url, echo=False)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

from sqlalchemy.sql import text

def init_db():
    Base.metadata.create_all(bind=engine)
    try:
        with engine.begin() as conn:
            conn.execute(text("ALTER TABLE customers ADD COLUMN is_blocked BOOLEAN DEFAULT FALSE;"))
    except Exception as e:
        # Column likely already exists
        pass
